
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '1088123BB310D19015EFB9132DE1565B'
    
_lr_action_items = {'LBRACE':([0,1,2,3,4,5,6,7,8,9,10,11,12,15,16,17,21,],[2,-1,2,-12,2,-4,-5,2,-2,-9,2,-10,-11,-6,-3,-7,-8,]),'WORD':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,21,],[3,-1,3,-12,3,-4,-5,3,-2,-9,3,-10,-11,3,3,-6,-3,-7,3,-8,]),'RBRACE':([1,3,5,6,7,8,15,16,17,21,],[-1,-12,-4,-5,15,-2,-6,-3,-7,-8,]),'UNION':([1,3,4,5,6,7,8,15,16,17,21,],[-1,-12,9,-4,-5,9,-2,-6,-3,-7,-8,]),'RPAREN':([3,20,],[-12,21,]),'RANGE':([3,5,],[-12,13,]),'COLON':([3,18,],[-12,19,]),'LPAREN':([3,5,],[-12,14,]),'DIFF':([1,3,4,5,6,7,8,15,16,17,21,],[-1,-12,11,-4,-5,11,-2,-6,-3,-7,-8,]),'INTER':([1,3,4,5,6,7,8,15,16,17,21,],[-1,-12,12,-4,-5,12,-2,-6,-3,-7,-8,]),'$end':([1,3,4,5,6,8,15,16,17,21,],[-1,-12,0,-4,-5,-2,-6,-3,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'operator':([4,7,],[10,10,]),'expr':([0,2,],[4,7,]),'multi':([0,2,4,7,10,],[1,1,8,8,16,]),'range':([0,2,4,7,10,],[6,6,6,6,6,]),'term':([0,2,4,7,10,13,14,19,],[5,5,5,5,5,17,18,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> multi','expr',1,'p_expr','Yacci.py',4),
  ('expr -> expr multi','expr',2,'p_expr','Yacci.py',5),
  ('expr -> expr operator multi','expr',3,'p_expr','Yacci.py',6),
  ('multi -> term','multi',1,'p_multi','Yacci.py',10),
  ('multi -> range','multi',1,'p_multi','Yacci.py',11),
  ('multi -> LBRACE expr RBRACE','multi',3,'p_multi','Yacci.py',12),
  ('range -> term RANGE term','range',3,'p_range','Yacci.py',16),
  ('range -> term LPAREN term COLON term RPAREN','range',6,'p_range','Yacci.py',17),
  ('operator -> UNION','operator',1,'p_operator','Yacci.py',21),
  ('operator -> DIFF','operator',1,'p_operator','Yacci.py',22),
  ('operator -> INTER','operator',1,'p_operator','Yacci.py',23),
  ('term -> WORD','term',1,'p_term','Yacci.py',27),
]
